#eureka:
# client:
#     serviceUrl:
#       defaultZone: http://192.168.10.25:8761/eureka/
# instance:
#   prefer-ip-address: true
#
#inventory-service :
#   ribbon.NFLoadBalancerRuleClassName : com.netflix.loadbalancer.RandomRule
    
feign:
  hystrix:
    enabled: true